#!/usr/bin/env ruby

# Influenced by
# http://barkingiguana.com/2009/01/25/scriptconsole-for-your-application/

libs = []
libs << File.expand_path(File.dirname(__FILE__) + '/../environment')

command_line = []
command_line << 'pry'
command_line << libs.inject('') {|acc, lib| acc + %( -r "#{lib}")}
command = command_line.join(' ')

exec command
